[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

[project]
name = "lfp-build"
version = "0.0.1+g7352469"
description = "Local build utilities"
requires-python = ">=3.11,<3.14"
dependencies = ["uv>=0.9.9", "ruff", "tomlkit", "mergedeep", "typer"]

#test123
[dependency-groups]
dev = ["pytest"]

[project.scripts]
lfp-build = "lfp_build.cli:main"

[tool.uv.workspace]
